[package]
name = "shizuku"
version = "0.1.0"
edition = "2024"

[dependencies]
llvm-sys = "181"
anyhow = "1.0.94"
colored = "2.1.0"
ecow = "0.2.3"
syntect = { version = "5.2.0", features = ["parsing"] }
